---
name: Acme-Hello
version: 0.03
author: ~
abstract: ~
license: perl
requires:
  perl: 5.005
recommends:
  Locale::Maketext: 0.20
  Locale::Maketext::Lexicon: 0.15
provides:
  Acme::Hello:
    file: lib/Acme/Hello.pm
    version: 0.03
  Acme::Hello::I18N:
    file: lib/Acme/Hello/I18N.pm
    version: 0.02
  Acme::Hello::I18N::_stub:
    file: lib/Acme/Hello/I18N.pm
    version: 0.02
generated_by: Module::Build version 0.2611
